name: Manual Playwright Automation trigger
on: workflow_dispatch
jobs:
  manual-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Bye"

